baseURL = 'https://massimilianofurlan.github.io'
languageCode = 'en-us'
title = 'Massimiliano Furlan'
theme = "researcher"
googleAnalytics = "7tdl8at7CNbIgx1GLlN6MIRht_sIIkgwWZSncgesciQ"
math = true
disableKinds = ["taxonomy", "term"]

[params]
  [params.style]
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    #avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 1
  [[menu.main]]
    name = "PGP"
    url = "/public-key.txt"
    weight = 2
  [[menu.main]]
    name = "Bookmarks"
    url = "/bookmarks"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files